### ISSUE TITLE
Error (euros) lib/euros/core.ex:18: Euros.Core.crawl/2

### ISSUE THREAD

**Issue by kytiken** [kytiken/euros#22]
```
iex> Euros.Core.crawl("https://euros-test.blogspot.jp", fn(page) -> IO.puts(inspect(page.request_url)) end)
:ok
iex> Euros.Core.crawl("https://euros-test.blogspot.jp", fn(page) -> page end)
** (MatchError) no match of right hand side value: {:error, {:already_started, #PID<0.185.0>}}
    (euros) lib/euros/core.ex:18: Euros.Core.crawl/2
```

**Comment by kytiken** [comment]
This issue is resolved by #25 .
