### ISSUE TITLE
no function clause matching in Euros.Page.link_uris/2

### ISSUE THREAD

**Issue by kytiken** [kytiken/euros#41]
```
** (FunctionClauseError) no function clause matching in Euros.Page.link_uris/2
    (euros) lib/euros/page.ex:39: Euros.Page.link_uris(%HTTPoison.Error{id: nil, reason: :bad_request}, ~r/.*/)
    (euros) lib/euros/core.ex:43: Euros.Core.do_crawl/5
    (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:36: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<0.8373981/0 in Euros.Core.crawl_task/5>
    Args: []
```

**Comment by kytiken** [comment]
This issue resolved by #42 .
